let mockSearch = [
  {
    id: 1,
    city1: "San Diego",
    city2: "Seattle",
    city3: "Austin",
    housing: 7,
    costofliving: 6,
    startups: 3,
    capital: 1,
    travel: 1,
    commute: 5,
    business: 8,
    safety: 1,
    healthcare: 8,
    education: 4,
    environment: 7,
    economy: 6,
    taxation: 4,
    internetaccess: 5,
    leisure: 4,
    tolerance: 7,
    outdoors: 3,
    user_id: 1,
  },
  {
    id: 2,
    city1: "San Jose",
    city2: "San Francisco",
    city3: "Dallas",
    housing: 7,
    costofliving: 6,
    startups: 3,
    capital: 1,
    travel: 1,
    commute: 5,
    business: 8,
    safety: 1,
    healthcare: 8,
    education: 4,
    environment: 7,
    economy: 6,
    taxation: 4,
    internetaccess: 5,
    leisure: 4,
    tolerance: 7,
    outdoors: 3,
    user_id: 2,
  },
];

export default mockSearch;
